# Generated by Django 5.2.8 on 2025-11-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommonCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50, verbose_name="코드분류")),
                ("code", models.CharField(max_length=50, verbose_name="코드")),
                ("description", models.CharField(max_length=100, verbose_name="설명")),
            ],
            options={
                "verbose_name": "공통 코드",
                "db_table": "common_codes",
                "unique_together": {("category", "code")},
            },
        ),
    ]
